---
- name: create systemd service unit
  template:
    src: sachet.service.j2
    dest: /etc/systemd/system/sachet.service
    owner: root
    group: root
    mode: 0644
  notify: restart sachet

- name: Create sachet main configuration file
  template:
    src: sachet.yml.j2
    dest: /etc/sachet.yml
    owner: root
    group: sachet
    mode: 0640
  notify: restart sachet

- name: Enable and start Sachet systemd unit
  systemd:
    name: sachet
    enabled: true
    state: started
    daemon_reload: true
