---

- name: create sachet system group
  group:
    name: sachet
    system: true
    state: present

- name: create sachet system user
  user:
    name: sachet
    system: true
    shell: "/sbin/nologin"
    group: sachet
    createhome: false

- name: download sachet binary to local folder
  become: false
  get_url:
    url: "https://{{ sachet_repository }}/releases/download/{{ sachet_version }}/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: unpack sachet binaries
  become: false
  unarchive:
    src: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}"
  delegate_to: localhost
  check_mode: false

- name: propagate sachet binaries
  copy:
    src: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - sachet
  notify:
    - restart alertmanager